version: "3.9"

services:
  auth-admin:
    container_name: auth-admin
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    networks:
      - traefik-public

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"

      - "traefik.http.services.auth-admin.loadbalancer.server.port=4173"

      - "traefik.http.middlewares.auth-admin-strip.stripprefix.prefixes=/auth-admin"

      - "traefik.http.routers.auth-admin.rule=Host(`sesc-it-team.ru`) && PathPrefix(`/auth-admin`)"
      - "traefik.http.routers.auth-admin.entrypoints=websecure"
      - "traefik.http.routers.auth-admin.tls.certresolver=letsencrypt"
      - "traefik.http.routers.auth-admin.priority=200"
      - "traefik.http.routers.auth-admin.middlewares=auth-admin-strip"
      - "traefik.http.routers.auth-admin.service=auth-admin"

networks:
  traefik-public:
    external: true