version: "3.9"

services:
  auth-admin:
    container_name: auth-admin
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public

      - traefik.http.routers.auth-admin.rule=Host(`auth.sesc-it-team.ru`) && PathPrefix(`/auth-admin`)
      - traefik.http.routers.auth-admin.entrypoints=websecure
      - traefik.http.routers.auth-admin.tls=true
      - traefik.http.routers.auth-admin.service=auth-admin

      - traefik.http.services.auth-admin.loadbalancer.server.port=4173

networks:
  traefik-public:
    external: true