version: "3.9"

services:
  auth-admin:
    container_name: auth-admin
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DOMAIN: ${DOMAIN}
      AUTH_DOMAIN: ${AUTH_DOMAIN}

    networks:
      - traefik-public
      - logging

    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik-public"

      traefik.http.services.auth-admin.loadbalancer.server.port: "4173"

      traefik.http.routers.auth-admin.rule: "Host(`${DOMAIN}`) && PathPrefix(`/auth-admin`)"
      traefik.http.routers.auth-admin.entrypoints: "websecure"
      traefik.http.routers.auth-admin.tls: "true"
      traefik.http.routers.auth-admin.tls.certresolver: "letsencrypt"
      traefik.http.routers.auth-admin.priority: "200"
      traefik.http.routers.auth-admin.service: "auth-admin"

      logging: "alloy"
      service: "lyceum-auth-admin-frontend"
      environment: "production"

networks:
  traefik-public:
    external: true
    name: traefik-public
  logging:
    external: true
    name: logging
